## ndarray 생성하기

- *n차원의 배열*

In [3]:
import numpy as np

data1 = [1, 2 ,3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [5]:
# arr = np.array([[1, 2], [3, 4, 5]]) # error: 안쪽 리스트의 배열이 달라서

In [7]:
print(arr1.ndim) # n차원
print(arr2.ndim)

1
2


In [8]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [9]:
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.zeros((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [12]:
print(np.zeros((2, 2, 3, 3)))

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [14]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
