## ndarray 자료형

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
# 생성할 때 속성을 넣어서 형변환
arr2 = np.array([1, 2, 3], dtype=np.float64)
arr3 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
int32


In [4]:
# 명시적 형변환
float_arr1 = arr1.astype(np.float64)
print(arr1)
print(float_arr1)
print(float_arr1.dtype)

[1 2 3]
[1. 2. 3.]
float64


In [6]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 형변환 시 소수점 버림
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64
