## 산술 연산

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# 같은 위치에 있는 데이터끼리 사칙연산
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [3]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr2 > arr)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[ True False False]
 [False False False]]
[[ True False False]
 [False False  True]]
