## 색인(인덱싱)과 슬라이싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [4]:
arr[2:5] = 10
print(arr) # 원본이 변함

[ 0  1 10 10 10  5  6  7  8  9]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][1])
print(arr[1, 1])

[[1 2 3]
 [4 5 6]]
5
5


In [13]:
arr3d = np.arange(27)
arr3d = arr3d.reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

19
19


In [21]:
arr3d[:1, 1:, 2:] # 슬라이싱 접근 대괄호 유지

array([[[5],
        [8]]])

In [24]:
arr3d[0, 1:, 2:] # 인덱스 접근 대괄호 -1

array([[5],
       [8]])

In [25]:
arr3d[0, 1:, 2:] = 999
print(arr3d)

[[[  0   1   2]
  [  3   4 999]
  [  6   7 999]]

 [[  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]]]
