## 팬시 색인(fancy indexing)

In [1]:
import numpy as np

In [3]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [4]:
arr[[4, 3, 0, 5]]
# 대괄호 안 대괄호 -> 내가 원하는 행을 직접 고를 수 있음

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [5]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [8]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [11]:
print(arr[[1, 5], [1, 3]])

[ 5 23]


In [19]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])