## numpy 함수

In [1]:
import numpy as np

In [6]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[-1.06531394 -0.4624275   0.96226824]
 [ 2.00397286 -1.10624337 -0.10298507]
 [-1.46938202 -0.82882659 -0.55652722]]


In [8]:
arr1 = np.sqrt(samples) # 음수에 루트 씌우면 결측치(nan: nor a number)
print(arr1)

[[       nan        nan 0.98095272]
 [1.41561748        nan        nan]
 [       nan        nan        nan]]


C:\Users\1-14\AppData\Local\Temp\ipykernel_7676\493222594.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) # 음수에 루트 씌우면 결측치(nan: nor a number)


In [9]:
arr2 = np.abs(samples) # absolute: 절댓값
print(arr2)

[[1.06531394 0.4624275  0.96226824]
 [2.00397286 1.10624337 0.10298507]
 [1.46938202 0.82882659 0.55652722]]


In [10]:
np.isnan(arr1) # 결측치 찾기

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])