## 00. numpy

In [2]:
import numpy as np # numpy: 배열 다루기에 특화

- 0차원: 스칼라(scala)
- 1차원: 벡터(vector)
- 2차원: 행렬(matrix)
- 3차원: 텐서(tenser)

In [4]:
a = [
    [1, 2.3, 3],
    [-123, 123, 0]
] # 2차원 리스트
data = np.array(a)
print(data)

[[   1.     2.3    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)
print(data + data)

[[   10.    23.    30.]
 [-1230.  1230.     0.]]
[[   2.     4.6    6. ]
 [-246.   246.     0. ]]


In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


## 1. ndarray 생성하기

- *n차원의 배열*

In [11]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([[1.1, 2.2], [3.3, 4.4, 5.5]]) # error: 안쪽 리스트의 배열이 달라서

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
print(arr1.ndim) # n차원
print(arr2.ndim)

1
2


In [14]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [15]:
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.zeros((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [16]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 2. ndarray 자료형

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype=np.float64) # 생성할 때 속성을 넣어서 형변환
arr3 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
int32


In [19]:
float_arr1 = arr1.astype(np.float64) # 명시적 형변환
print(arr1)
print(float_arr1)
print(float_arr1.dtype)

[1 2 3]
[1. 2. 3.]
float64


In [20]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 형변환 시 소수점 버림
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 3. 산술 연산

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) # 같은 위치에 있는 데이터끼리 사칙연산
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [22]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[ True False False]
 [False False  True]]


## 4. 색인(인덱싱)과 슬라이싱

In [23]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [25]:
arr[2:5] = 10
print(arr) # 원본이 변함

[ 0  1 10 10 10  5  6  7  8  9]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][1])
print(arr[1, 1])

[[1 2 3]
 [4 5 6]]
5
5


In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [31]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [34]:
arr3d[:1, 1:, 2:] # 슬라이싱 접근 대괄호 유지

array([[[6],
        [9]]])

In [37]:
arr3d[0, 1:, 2:] # 인덱스 접근 대괄호 -1

array([[6],
       [9]])

In [38]:
arr3d[0, 1:, 2:] = 999
print(arr3d)

[[[  1   2   3]
  [  4   5 999]
  [  7   8 999]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]]


## 5. 불리언 값으로 선택

In [39]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [40]:
names == 'hong'

array([ True, False,  True, False])

In [41]:
data[[True, False, True, False]]

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [42]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [43]:
names = np.array(['hong', 'kim', 'kim', 'hong'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [44]:
data[names == 'hong'] # 순서로 고름

array([['math', '60'],
       ['eng', '50']], dtype='<U21')

In [46]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '50']
[['math']
 ['eng']]


In [47]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True  True False]
[False  True  True False]


In [48]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '70']], dtype='<U21')

## 6. 팬시 색인 (fancy indexing)

In [49]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [50]:
arr[[4, 3, 0, 5]] # 대괄호 안 대괄호 -> 내가 원하는 행을 직접 고를 수 있음

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [51]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [52]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [58]:
print(arr[[1, 5], [2, 3]])

[ 6 23]


In [59]:
print(arr[[1, 5], [1, 2]])

[ 5 22]


In [63]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 7. 배열 전치

In [3]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(arr.T) # 축을 바꿀 때

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
# 행렬의 내적, 곱 연산
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## 8. numpy 함수

In [7]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[-0.70258835 -0.34174114  0.65235979]
 [ 0.71713773  0.5360125  -2.08544605]
 [ 1.06071122 -0.38576056  0.44127118]]


In [8]:
arr1 = np.sqrt(samples) # 루트에 루트 씌우면 결측치(nan: not a number)
print(arr1)

[[       nan        nan 0.80768793]
 [0.84683985 0.73212875        nan]
 [1.02990835        nan 0.66428245]]


C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1273485535.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [9]:
arr2 = np.abs(samples) # absolute: 절댓값
print(arr2)

[[0.70258835 0.34174114 0.65235979]
 [0.71713773 0.5360125  2.08544605]
 [1.06071122 0.38576056 0.44127118]]


In [11]:
np.isnan(arr1) # 결측치 찾기

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False]])

# 01. data structure

## 1. Series

- pandas에서 사용하는 1차원 배열
- index를 사용할 수 있음

In [1]:
import pandas as pd
import numpy as np

In [13]:
arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [14]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [16]:
s = pd.Series(arr, dtype='float32')
print(s)

0    100.0
1    101.0
2    102.0
3    103.0
4    104.0
5    105.0
6    106.0
7    107.0
8    108.0
9    109.0
dtype: float32


In [18]:
s = pd.Series(['kim', 'lee', 'park'])
print(s) # pandas에서 object = str

0     kim
1     lee
2    park
dtype: object


In [19]:
s = pd.Series([1, 2, 3, '1', '2', 'hello'])
print(s) # object: 포괄적인 데이터 타입

0        1
1        2
2        3
3        1
4        2
5    hello
dtype: object


In [20]:
s[5]

'hello'

In [21]:
s[-1] # errpr: 음수 인덱싱 X

KeyError: -1

In [22]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [23]:
names = pd.Series(['kim', 'lee', 'park'], index=['a', 'b', 'c'])
names # 인덱스가 숫자가 아니어도 됨

a     kim
b     lee
c    park
dtype: object

In [24]:
names[0] # 인덱싱 가능하지만 가능하면 iloc 사용

C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1035344546.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  names[0]


'kim'

In [25]:
names.iloc[0] # index location

'kim'

In [26]:
names['a']

'kim'

In [27]:
names.index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
names.values

array(['kim', 'lee', 'park'], dtype=object)

In [29]:
names.ndim

1

In [30]:
names.shape

(3,)

## 2. NaN (Not a Number)

In [32]:
s = pd.Series([1, 2, 3, np.nan])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


## 3. fancy indexing

In [33]:
f = ['banana', 'apple', 'grape', np.nan]
s = pd.Series(f, index=list('abcd'))
print(s)

a    banana
b     apple
c     grape
d       NaN
dtype: object


In [34]:
s[['d', 'a']]

d       NaN
a    banana
dtype: object

In [35]:
s[[3, 1]] # 숫자 쓸 땐 iloc 사용

C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1367491741.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[3, 1]]


d      NaN
b    apple
dtype: object

In [36]:
s.iloc[[3, 1]]

d      NaN
b    apple
dtype: object

## 4. bool indexing

In [37]:
s

a    banana
b     apple
c     grape
d       NaN
dtype: object

In [38]:
s[[True, False, True, False]]

a    banana
c     grape
dtype: object

In [39]:
s == 'banana'

a     True
b    False
c    False
d    False
dtype: bool

In [40]:
s[s == 'banana']

a    banana
dtype: object

In [41]:
s = pd.Series([1, 5, 3, 4, 2, 6])
s[s > 3]

1    5
3    4
5    6
dtype: int64

## 5. 결측치(NaN) 처리

In [42]:
s = pd.Series([1, 3, np.nan, 10, 11, np.nan])
print(s)

0     1.0
1     3.0
2     NaN
3    10.0
4    11.0
5     NaN
dtype: float64


In [43]:
s. isnull()
s. isna()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [44]:
s[s.isnull()]
s[s.isna()]

2   NaN
5   NaN
dtype: float64

In [45]:
s[s.notnull()]
s[s.notna()]

0     1.0
1     3.0
3    10.0
4    11.0
dtype: float64

## 6. Slicing

In [46]:
s[1:3]

1    3.0
2    NaN
dtype: float64

In [48]:
s = pd.Series([1, 2, 3], index=list('abc'))
print(s[1:2])
print(s['a':'b']) # 글자는 이상 미만이 안됨

b    2
dtype: int64
a    1
b    2
dtype: int64


## 7. DataFrame

- 2차원 데이터구조 (excel, sheet와 유사)
- 행(row), 열(column) 구조

In [2]:
d = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
d

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
d = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], columns=list('가나다'))
d

가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
info = {
    'name': ['kim', 'lee', 'park'],
    'age' : [10, 20, 30]
}

In [6]:
info_df = pd.DataFrame(info)
info_df

name  age
0   kim   10
1   lee   20
2  park   30

In [8]:
info_df.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
info_df.columns

Index(['name', 'age'], dtype='object')

In [11]:
info_df.values

array([['kim', 10],
       ['lee', 20],
       ['park', 30]], dtype=object)

In [12]:
info_df.dtypes

name    object
age      int64
dtype: object

In [13]:
info_df.T

0    1     2
name  kim  lee  park
age    10   20    30

## 8. index 지정

In [14]:
info_df.index = list('abc')
info_df

name  age
a   kim   10
b   lee   20
c  park   30

## 9. column 다루기

In [15]:
info_df.columns

Index(['name', 'age'], dtype='object')

In [16]:
print(info_df['name'])
print(type(info_df['name']))

a     kim
b     lee
c    park
Name: name, dtype: object
<class 'pandas.core.series.Series'>


In [17]:
info_df[['age', 'name']] # column의 fancy indexing

age  name
a   10   kim
b   20   lee
c   30  park

In [18]:
info_df = info_df.rename(columns={'name': '이름'}) # 재할당해서 원본 변경
info_df

이름  age
a   kim   10
b   lee   20
c  park   30

In [19]:
info_df.rename(columns={'이름': 'last name'}, inplace=True) # 바로 변경
info_df

last name  age
a       kim   10
b       lee   20
c      park   30

# 02. file load save

In [20]:
import numpy as np
import pandas as pd

## 1. excel

```python
excel = pd.read_excel('파일위치/파일명.xlsx') # 불러오기
excel[['colum1', 'column2', ...]] # indexing
excel.head()
excel = pd.read_excel('data/excel.xlsx', sheet_name=None) # dictionary
excel = pd.read_excel('data/excel.xlsx', sheet_name='시트이름')
excel.to_excel('파일위치/파일명.xlsx', index=False) # 저장
```

## 2. CSV

```python
df = pd.read_csv('파일위치/파일명.csv')
df.to_csv('파일위치/파일명.csv')
```

# 03. query

In [1]:
import pandas as pd
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [2]:
df = sns.load_dataset('titanic')

## 1. head(), tail()

In [27]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [28]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

## 2. info()

In [29]:
df.info()
# non-null: 결측치가 아닌 정보를 세어줌
# category: 분류가 되는 데이터

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


## 3. value_counts()

In [30]:
df['who']

0        man
1      woman
2      woman
3      woman
4        man
       ...  
886      man
887    woman
888    woman
889      man
890      man
Name: who, Length: 891, dtype: object

In [31]:
print(type(df['who'])) # column 1개 = Series

<class 'pandas.core.series.Series'>


In [32]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

## 4. Attribute

In [33]:
df.ndim # dataframe은 사실상 모두 2차원

2

In [34]:
df.shape # 데이터 891개, 칼럼 15개

(891, 15)

In [35]:
df.index # 데이터의 개수

RangeIndex(start=0, stop=891, step=1)

In [38]:
df.columns # 칼럼만 보기

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [39]:
df.values # 값만 보기

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]],
      shape=(891, 15), dtype=object)

## 5. 타입 변환 (astype)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [41]:
df['pclass'].astype('int32')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int32

In [42]:
df['pclass'].astype('str')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: object

In [43]:
df['pclass'].astype('category')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: category
Categories (3, int64): [1, 2, 3]

## 6. 정렬

### 6.1. sort_index()

In [5]:
df.sort_index(ascending=False).head() # ascending: 오름차순/ =False: 내림차순

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
890         0       3    male  32.0      0      0   7.75        Q   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
887         1       1  female  19.0      0      0  30.00        S   First   
886         0       2    male  27.0      0      0  13.00        S  Second   

       who  adult_male deck  embark_town alive  alone  
890    man        True  NaN   Queenstown    no   True  
889    man        True    C    Cherbourg   yes   True  
888  woman       False  NaN  Southampton    no  False  
887  woman       False    B  Southampton   yes   True  
886    man        True  NaN  Southampton    no   True

### 6.2. sort_values()

In [6]:
df.sort_values('age').head()

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
803         1       3    male  0.42      0      1   8.5167        C   Third   
755         1       2    male  0.67      1      1  14.5000        S  Second   
644         1       3  female  0.75      2      1  19.2583        C   Third   
469         1       3  female  0.75      2      1  19.2583        C   Third   
78          1       2    male  0.83      0      2  29.0000        S  Second   

       who  adult_male deck  embark_town alive  alone  
803  child       False  NaN    Cherbourg   yes  False  
755  child       False  NaN  Southampton   yes  False  
644  child       False  NaN    Cherbourg   yes  False  
469  child       False  NaN    Cherbourg   yes  False  
78   child       False  NaN  Southampton   yes  False

In [7]:
df.sort_values('class').head() # 문자는 알파벳순

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
445         1       1    male   4.0      0      2   81.8583        S  First   
310         1       1  female  24.0      0      0   83.1583        C  First   
309         1       1  female  30.0      0      0   56.9292        C  First   
307         1       1  female  17.0      1      0  108.9000        C  First   
306         1       1  female   NaN      0      0  110.8833        C  First   

       who  adult_male deck  embark_town alive  alone  
445  child       False    A  Southampton   yes  False  
310  woman       False    C    Cherbourg   yes   True  
309  woman       False    E    Cherbourg   yes   True  
307  woman       False    C    Cherbourg   yes  False  
306  woman       False  NaN    Cherbourg   yes   True

In [9]:
df.sort_values(['fare', 'age'], ascending=[False,True]).head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
679         1       1    male  36.0      0      1  512.3292        C  First   
27          0       1    male  19.0      3      2  263.0000        S  First   
88          1       1  female  23.0      3      2  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
258  woman       False  NaN    Cherbourg   yes   True  
737    man        True    B    Cherbourg   yes   True  
679    man        True    B    Cherbourg   yes  False  
27     man        True    C  Southampton    no  False  
88   woman       False    C  Southampton   yes  False

## 7. indexing, slicing, 조건 필터링

- *indexing: 하나를 고를 때*
- *slcing: 여기서부터 여기까지 고를 때*
- *조건 필터링: 조건에 맞는 걸 고를 때*

In [10]:
df.loc[3]

survived                 1
pclass                   1
sex                 female
age                   35.0
sibsp                    1
parch                    0
fare                  53.1
embarked                 S
class                First
who                  woman
adult_male           False
deck                     C
embark_town    Southampton
alive                  yes
alone                False
Name: 3, dtype: object

In [11]:
df.loc[3, 'class']

'First'

In [12]:
df.loc[3, ['class', 'age']] # 한 사람의 데이터 - 시리즈 형태

class    First
age       35.0
Name: 3, dtype: object

In [13]:
df.loc[2:5] # 파이썬과 다른 점: 마지막 데이터가 포함됨

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [14]:
df.loc[2:5, ['pclass', 'who']] # 여러 사람의 데이터 - 데이터 프레임 형태

pclass    who
2       3  woman
3       1  woman
4       3    man
5       3    man

In [15]:
df[['class']].head() # [[]]: 데이터 프레임 형태로 가져옴(여러개의 칼럼을 가져온다는 의미)

class
0  Third
1  First
2  Third
3  First
4  Third

In [16]:
df.loc[:3, 'class':'deck'] # 칼럼으로 슬라이싱

class    who  adult_male deck
0  Third    man        True  NaN
1  First  woman       False    C
2  Third  woman       False  NaN
3  First  woman       False    C

In [17]:
df['who'] == 'man' # 데이터를 전부 비교

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888    False
889     True
890     True
Name: who, Length: 891, dtype: bool

In [18]:
condition = df['who'] == 'man'
df[condition].head()

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
0          0       3  male  22.0      1      0   7.2500        S  Third  man   
4          0       3  male  35.0      0      0   8.0500        S  Third  man   
5          0       3  male   NaN      0      0   8.4583        Q  Third  man   
6          0       1  male  54.0      0      0  51.8625        S  First  man   
12         0       3  male  20.0      0      0   8.0500        S  Third  man   

    adult_male deck  embark_town alive  alone  
0         True  NaN  Southampton    no  False  
4         True  NaN  Southampton    no   True  
5         True  NaN   Queenstown    no   True  
6         True    E  Southampton    no   True  
12        True  NaN  Southampton    no   True

In [19]:
df.loc[condition].head() # loc 쓰기 권장

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
0          0       3  male  22.0      1      0   7.2500        S  Third  man   
4          0       3  male  35.0      0      0   8.0500        S  Third  man   
5          0       3  male   NaN      0      0   8.4583        Q  Third  man   
6          0       1  male  54.0      0      0  51.8625        S  First  man   
12         0       3  male  20.0      0      0   8.0500        S  Third  man   

    adult_male deck  embark_town alive  alone  
0         True  NaN  Southampton    no  False  
4         True  NaN  Southampton    no   True  
5         True  NaN   Queenstown    no   True  
6         True    E  Southampton    no   True  
12        True  NaN  Southampton    no   True

In [20]:
# df.loc[condition]['age'] = 100 -> 안되는 코드
df.loc[condition, 'age'] = 100 # 숫자를 일괄적으로 채움
df.head()

survived  pclass     sex    age  sibsp  parch     fare embarked  class  \
0         0       3    male  100.0      1      0   7.2500        S  Third   
1         1       1  female   38.0      1      0  71.2833        C  First   
2         1       3  female   26.0      0      0   7.9250        S  Third   
3         1       1  female   35.0      1      0  53.1000        S  First   
4         0       3    male  100.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [21]:
cond1 = df['fare'] > 30
cond2 = df['who'] == 'woman'

df.loc[cond1 & cond2].head() # 둘 다 만족하는 경우

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1          1       1  female  38.0      1      0   71.2833        C  First   
3          1       1  female  35.0      1      0   53.1000        S  First   
25         1       3  female  38.0      1      5   31.3875        S  Third   
31         1       1  female   NaN      1      0  146.5208        C  First   
52         1       1  female  49.0      1      0   76.7292        C  First   

      who  adult_male deck  embark_town alive  alone  
1   woman       False    C    Cherbourg   yes  False  
3   woman       False    C  Southampton   yes  False  
25  woman       False  NaN  Southampton   yes  False  
31  woman       False    B    Cherbourg   yes  False  
52  woman       False    D    Cherbourg   yes  False

In [22]:
df.loc[cond1 | cond2].head() # 하나라도 만족하는 경우

survived  pclass     sex    age  sibsp  parch     fare embarked  class  \
1         1       1  female   38.0      1      0  71.2833        C  First   
2         1       3  female   26.0      0      0   7.9250        S  Third   
3         1       1  female   35.0      1      0  53.1000        S  First   
6         0       1    male  100.0      0      0  51.8625        S  First   
8         1       3  female   27.0      0      2  11.1333        S  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
6    man        True    E  Southampton    no   True  
8  woman       False  NaN  Southampton   yes  False

In [23]:
df.iloc[1, 3] # index를 숫자로 접근할 때 사용/ 1번 데이터의 3번 칼럼

np.float64(38.0)

In [24]:
df.iloc[1:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

In [25]:
df.iloc[1:3, 2:5]

sex   age  sibsp
1  female  38.0      1
2  female  26.0      0

## 8. where()

- 조건이 False인 데이터를 일괄적으로 수정하는 함수

In [26]:
cond = df['fare'] < 30
df['fare'].where(cond, 1).tail()

886    13.00
887     1.00
888    23.45
889     1.00
890     7.75
Name: fare, dtype: float64

## isin()

In [29]:
# cond1 = df['embarked'] == 'Q'
# cond2 = df['embarked'] == 'S'

cond = df['embarked'].isin(['Q', 'S']) # 여러개의 조건을 같이 쓸 때
df.loc[cond].head()

survived  pclass     sex    age  sibsp  parch     fare embarked  class  \
0         0       3    male  100.0      1      0   7.2500        S  Third   
2         1       3  female   26.0      0      0   7.9250        S  Third   
3         1       1  female   35.0      1      0  53.1000        S  First   
4         0       3    male  100.0      0      0   8.0500        S  Third   
5         0       3    male  100.0      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

# 04. statistics

In [33]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

## 1. describe()

In [34]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [35]:
df.describe(include='object')

sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

## 2. count()

In [36]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [37]:
df['age'].count()

np.int64(714)

## 3. mean()

In [38]:
df['age'].mean()

np.float64(29.69911764705882)

In [41]:
# df.mean() -> error: 평균을 계산할 수 없는 것도 있어서
df.mean(numeric_only=True) # 숫자만
# df.mean(numeric_only=True, skipna=False) # NaN이 있을 경우 계산 안 함

survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64

In [46]:
# 성인 남성 요금 평균
cond = df['adult_male'] == True
df.loc[cond, 'fare'].mean()

np.float64(24.864181750465548)

In [48]:
# fare 30 ~ 40 지불 % 1등석 승객의 나이 평균
cond1 = df['fare'] >= 30
cond2 = df['fare'] <= 40
cond3 = df['pclass'] == 1

df.loc[cond1 & cond2 & cond3, 'age'].mean()

np.float64(44.095238095238095)

## 4. median()

In [49]:
numbers = [1, 2, 10, 11, 100, 1000]
pd.Series(numbers).mean()

np.float64(187.33333333333334)

In [50]:
pd.Series(numbers).median() 
# 중앙값: 데이터를 정렬하고 가운데를 고름
# 이상치가 너무 큰 상황에 사용

np.float64(10.5)

In [52]:
mean_value = df['age'].mean()
median_value = df['age'].median()

print(mean_value)
print(median_value) # 데이터가 크기 때문에 비슷한 값이 나옴

29.69911764705882
28.0


## 5. sum()

In [54]:
df.sum(numeric_only=True)

survived        342.0000
pclass         2057.0000
age           21205.1700
sibsp           466.0000
parch           340.0000
fare          28693.9493
adult_male      537.0000
alone           537.0000
dtype: float64

In [55]:
df['fare'].sum()

np.float64(28693.9493)

In [58]:
df['fare'].cumsum() # 누적합

0          7.2500
1         78.5333
2         86.4583
3        139.5583
4        147.6083
          ...    
886    28602.7493
887    28632.7493
888    28656.1993
889    28686.1993
890    28693.9493
Name: fare, Length: 891, dtype: float64

In [59]:
df['age'].cumprod() # 누적곱

C:\Users\Home10\Desktop\DAMF2\TIL\venv\Lib\site-packages\numpy\_core\fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)


0            22.0
1           836.0
2         21736.0
3        760760.0
4      26626600.0
          ...    
886           inf
887           inf
888           NaN
889           inf
890           inf
Name: age, Length: 891, dtype: float64

## 6. var() 분산

In [61]:
fare_mean = df['fare'].mean()

total = ((df['fare'] - fare_mean) ** 2).sum() # 시리즈는 스칼라 연산 가능
total_count = df['fare'].count() # 모분산
# total_count = df['fare'].count() - 1 # 표본분산

my_var = total/total_count
print(my_var)

2466.665311685043


In [62]:
df['fare'].var(ddof=0) # 모분

np.float64(2466.665311685043)

## 7. std()

In [63]:
import numpy as np

In [64]:
np.sqrt(df['fare'].var())

np.float64(49.6934285971809)

In [65]:
df['fare'].std()

np.float64(49.6934285971809)

## 8. min(), max()

In [66]:
df['age'].min()

np.float64(0.42)

In [67]:
df['age'].max()

np.float64(80.0)

## 9. agg() (aggregation)

In [68]:
df['age'].agg(['min', 'max', 'count', 'mean'])

min        0.420000
max       80.000000
count    714.000000
mean      29.699118
Name: age, dtype: float64

In [69]:
df[['age', 'fare']].agg(['min', 'max'])

age      fare
min   0.42    0.0000
max  80.00  512.3292

## 10. quantile()

In [70]:
df['age'].quantile(0.1) # 하위 10%

np.float64(14.0)

In [72]:
df['age'].quantile(0.8) # 상위 20%

np.float64(41.0)

In [73]:
df['age'].quantile(0.5) # 중앙값과 같음

np.float64(28.0)

## 11. unique()

In [74]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [75]:
df['who'].nunique()

3

## 12. mode() 최빈값

In [76]:
df['who'].mode()

0    man
Name: who, dtype: object

In [77]:
df['deck'].mode()

0    C
Name: deck, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

## 13. corr()

- 각 칼럼끼리의 상관관계를 -1 ~ 1로 표현
- *1과 가까울수록 정비례함, -1과 가까울수록 반비례함*
- *-1 or 1과 가까울수록 상관관계가 높음*

In [78]:
df.corr(numeric_only=True)

survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500   
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067   
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.280328  0.198270  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

In [80]:
df.corr(numeric_only=True)['survived']

survived      1.000000
pclass       -0.338481
age          -0.077221
sibsp        -0.035322
parch         0.081629
fare          0.257307
adult_male   -0.557080
alone        -0.203367
Name: survived, dtype: float64

# 05. missing value

In [85]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

### 1. copy

In [86]:
df_copy = df.copy()

In [87]:
id(df_copy), id(df) # 복제했기 때문에 둘은 서로 다른 데이터

(2115255733280, 2115255732496)

In [89]:
df_copy.loc[0, 'age'] = 9999

df_copy.head(1)

survived  pclass   sex     age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  9999.0      1      0  7.25        S  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False

In [90]:
df.head(1)

survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  22.0      1      0  7.25        S  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False

## 2. 결측치

1. 결측 데이터 **확인**
2. 결측치가 아닌 데이터 확인
---
1. 결측치 채우기
2. 결측 데이터 제거하기

In [91]:
df_copy = df.copy()

In [93]:
df_copy.isnull().sum() # isnull: null값이 있는지 # sum: 있으면 1을 모두 더함
# = df_copy.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [94]:
df_copy.notnull().sum() # 비어있지 않은 것 확인
# = df_copy.notna().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

## 2.1. 결측 데이터 필터링

In [95]:
cond = df_copy['age'].isnull() # 비어있는 데이터 골라내기
df_copy.loc[cond, 'age'] = 30 # 일괄적으로 적용하기
df_copy.tail() # 데이터 바뀐 것 확인하기

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female  30.0      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

## 2.2. fillna()

In [96]:
df_copy = df.copy()

In [97]:
df_copy['age'].fillna(100) # 연산 결과만 반영, 데이터프레임에 반영하지 않음

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
       ...  
886     27.0
887     19.0
888    100.0
889     26.0
890     32.0
Name: age, Length: 891, dtype: float64

In [99]:
df_copy['age'] = df_copy['age'].fillna(100) # 재할당

In [100]:
df_copy.tail()

survived  pclass     sex    age  sibsp  parch   fare embarked   class  \
886         0       2    male   27.0      0      0  13.00        S  Second   
887         1       1  female   19.0      0      0  30.00        S   First   
888         0       3  female  100.0      1      2  23.45        S   Third   
889         1       1    male   26.0      0      0  30.00        C   First   
890         0       3    male   32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [101]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [102]:
df_copy['deck'].value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [103]:
df_copy['deck'].fillna('C')

0      C
1      C
2      C
3      C
4      C
      ..
886    C
887    B
888    C
889    C
890    C
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [105]:
# df_copy['deck'].fillna('Z') -> error: 카테고리에 Z가 없어서 넣을 수 없음
df_copy['deck'] = df_copy['deck'].cat.add_categories('Z') # 카테고리 추가
df_copy['deck'].fillna('Z')

0      Z
1      C
2      Z
3      C
4      Z
      ..
886    Z
887    B
888    Z
889    C
890    Z
Name: deck, Length: 891, dtype: category
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'Z']

In [107]:
age_mean = df_copy['age'].mean() 
df_copy['age'] = df_copy['age'].fillna(age_mean) # 평균으로 채우기
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [109]:
df_copy = df.copy()
df_copy['age'] = df_copy['age'].fillna(df['age'].median()) # 중앙값으로 채우기
df_copy.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female  28.0      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

## 2.3. dropna()

In [110]:
df_copy = df.copy()

df_copy.dropna() # 하나라도 NaN이 있으면 지워줌

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
6      man        True    E  Southampton    no   True  
10   child       False    G  Southampton   yes  False  
11   woman       False    C  Southampton   yes   True  
..     ...         ...  ...          ...   ...    ...  
871  woman       False    D  Southampton   yes  False  
872    man        True    B  Southampton    no   True  
879  woman       False    C    Cherbourg   yes  False  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  

[182 rows x 15 columns]

In [111]:
df_copy.dropna(how='all') # 전체 데이터가 다 빠진 경우에만 지워줌

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# 06. preprocessing 전처리

In [112]:
import pandas as pd
import seaborn as sna

df = sns.load_dataset('titanic')
df_copy = df.copy()

## 1. 컬럼 추가

In [113]:
df_copy['VIP'] = False # 일괄적으로 똑같은 값
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  
0    man        True  NaN  Southampton    no  False  False  
1  woman       False    C    Cherbourg   yes  False  False  
2  woman       False  NaN  Southampton   yes   True  False  
3  woman       False    C  Southampton   yes  False  False  
4    man        True  NaN  Southampton    no   True  False

In [114]:
df_copy['family'] = df_copy['sibsp'] + df_copy['parch']
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  
0    man        True  NaN  Southampton    no  False  False       1  
1  woman       False    C    Cherbourg   yes  False  False       1  
2  woman       False  NaN  Southampton   yes   True  False       0  
3  woman       False    C  Southampton   yes  False  False       1  
4    man        True  NaN  Southampton    no   True  False       0

In [116]:
df_copy['gender'] = df_copy['sex'] + '-' + df_copy['who']
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
0    man        True  NaN  Southampton    no  False  False       1   
1  woman       False    C    Cherbourg   yes  False  False       1   
2  woman       False  NaN  Southampton   yes   True  False       0   
3  woman       False    C  Southampton   yes  False  False       1   
4    man        True  NaN  Southampton    no   True  False       0   

         gender  
0      male-man  
1  female-woman  
2  female-woman  
3  female-woman  
4      male-man

In [117]:
df_copy['f/a'] = round(df_copy['fare'] / df_copy['age'], 2) # round: 소수의 자릿수 계산
df_copy.head() # 컬럼을 합치는 것 = 특성공학

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
0    man        True  NaN  Southampton    no  False  False       1   
1  woman       False    C    Cherbourg   yes  False  False       1   
2  woman       False  NaN  Southampton   yes   True  False       0   
3  woman       False    C  Southampton   yes  False  False       1   
4    man        True  NaN  Southampton    no   True  False       0   

         gender   f/a  
0      male-man  0.33  
1  female-woman  1.88  
2  female-woman  0.30  
3  female-woman  1.52  
4      male-man  0.23

## 2. 삭제

### 2.1. 행삭제

In [118]:
df_copy.drop(1).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
0    man        True  NaN  Southampton    no  False  False       1   
2  woman       False  NaN  Southampton   yes   True  False       0   
3  woman       False    C  Southampton   yes  False  False       1   
4    man        True  NaN  Southampton    no   True  False       0   
5    man        True  NaN   Queenstown    no   True  False       0   

         gender   f/a  
0      male-man  0.33  
2  female-woman  0.30  
3  female-woman  1.52  
4      male-man  0.23  
5      male-man   NaN

In [120]:
df_copy.head() # 원본은 그대로, 연산이 바로 적용되지는 않음

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
0    man        True  NaN  Southampton    no  False  False       1   
1  woman       False    C    Cherbourg   yes  False  False       1   
2  woman       False  NaN  Southampton   yes   True  False       0   
3  woman       False    C  Southampton   yes  False  False       1   
4    man        True  NaN  Southampton    no   True  False       0   

         gender   f/a  
0      male-man  0.33  
1  female-woman  1.88  
2  female-woman  0.30  
3  female-woman  1.52  
4      male-man  0.23

In [121]:
df_copy.drop(range(5)).head()

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
5    man        True  NaN   Queenstown    no   True  False       0   
6    man        True    E  Southampton    no   True  False       0   
7  child       False  NaN  Southampton    no  False  False       4   
8  woman       False  NaN  Southampton   yes  False  False       2   
9  child       False  NaN    Cherbourg   yes  False  False       1   

         gender    f/a  
5      male-man    NaN  
6      male-man   0.96  
7    male-child  10.54  
8  female-woman   0.41  
9  female-child   2.15

In [122]:
df_copy.drop([1, 3, 4, 7, 9]).head() # 인덱스를 활용하여 행을 지우는 법

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       3  female  26.0      0      0   7.9250        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
8         1       3  female  27.0      0      2  11.1333        S  Third   

     who  adult_male deck  embark_town alive  alone    VIP  family  \
0    man        True  NaN  Southampton    no  False  False       1   
2  woman       False  NaN  Southampton   yes   True  False       0   
5    man        True  NaN   Queenstown    no   True  False       0   
6    man        True    E  Southampton    no   True  False       0   
8  woman       False  NaN  Southampton   yes  False  False       2   

         gender   f/a  
0      male-man  0.33  
2  female-woman  0.30  
5      male-man   NaN  
6      male-man  0.96  
8  female-woman  0.41

### 2.2. 열삭제

In [124]:
df_copy.drop('VIP', axis=1).head()
# = df_copy.drop('VIP', axis='columns').head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  family        gender  \
0    man        True  NaN  Southampton    no  False       1      male-man   
1  woman       False    C    Cherbourg   yes  False       1  female-woman   
2  woman       False  NaN  Southampton   yes   True       0  female-woman   
3  woman       False    C  Southampton   yes  False       1  female-woman   
4    man        True  NaN  Southampton    no   True       0      male-man   

    f/a  
0  0.33  
1  1.88  
2  0.30  
3  1.52  
4  0.23

In [125]:
df_copy.drop(['deck', 'VIP', 'alive'], axis=1, inplace=True) # inplace: 바로 적용
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male  embark_town  alone  family        gender   f/a  
0    man        True  Southampton  False       1      male-man  0.33  
1  woman       False    Cherbourg  False       1  female-woman  1.88  
2  woman       False  Southampton   True       0  female-woman  0.30  
3  woman       False  Southampton  False       1  female-woman  1.52  
4    man        True  Southampton   True       0      male-man  0.23

## 3. 데이터 타입

In [126]:
df_copy =  df.copy()
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [127]:
df_copy['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [129]:
df_copy['who'] = df_copy['who'].astype('category')
df_copy['who'].dtype

CategoricalDtype(categories=['child', 'man', 'woman'], ordered=False, categories_dtype=object)

In [130]:
df_copy['who'].cat.codes

0      1
1      2
2      2
3      2
4      1
      ..
886    1
887    2
888    2
889    1
890    1
Length: 891, dtype: int8

In [131]:
df_copy['who'] = df_copy['who'].cat.rename_categories(['아이', '남자', '여자'])
df_copy['who'].value_counts()

who
남자    537
여자    271
아이     83
Name: count, dtype: int64

### 3.1. datetime

In [132]:
df.shape

(891, 15)

In [133]:
dates = pd.date_range('20250101', periods=df.shape[0], freq='15h')
# df.shape[0]: 데이터가 변경 가능성이 있기 때문에 891 대신 코드를 적어줌
dates

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 15:00:00',
               '2025-01-02 06:00:00', '2025-01-02 21:00:00',
               '2025-01-03 12:00:00', '2025-01-04 03:00:00',
               '2025-01-04 18:00:00', '2025-01-05 09:00:00',
               '2025-01-06 00:00:00', '2025-01-06 15:00:00',
               ...
               '2026-07-05 15:00:00', '2026-07-06 06:00:00',
               '2026-07-06 21:00:00', '2026-07-07 12:00:00',
               '2026-07-08 03:00:00', '2026-07-08 18:00:00',
               '2026-07-09 09:00:00', '2026-07-10 00:00:00',
               '2026-07-10 15:00:00', '2026-07-11 06:00:00'],
              dtype='datetime64[ns]', length=891, freq='15h')

In [134]:
df_copy['date'] = dates
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class who  \
0         0       3    male  22.0      1      0   7.2500        S  Third  남자   
1         1       1  female  38.0      1      0  71.2833        C  First  여자   
2         1       3  female  26.0      0      0   7.9250        S  Third  여자   
3         1       1  female  35.0      1      0  53.1000        S  First  여자   
4         0       3    male  35.0      0      0   8.0500        S  Third  남자   

   adult_male deck  embark_town alive  alone                date  
0        True  NaN  Southampton    no  False 2025-01-01 00:00:00  
1       False    C    Cherbourg   yes  False 2025-01-01 15:00:00  
2       False  NaN  Southampton   yes   True 2025-01-02 06:00:00  
3       False    C  Southampton   yes  False 2025-01-02 21:00:00  
4        True  NaN  Southampton    no   True 2025-01-03 12:00:00

In [135]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   survived     891 non-null    int64         
 1   pclass       891 non-null    int64         
 2   sex          891 non-null    object        
 3   age          714 non-null    float64       
 4   sibsp        891 non-null    int64         
 5   parch        891 non-null    int64         
 6   fare         891 non-null    float64       
 7   embarked     889 non-null    object        
 8   class        891 non-null    category      
 9   who          891 non-null    category      
 10  adult_male   891 non-null    bool          
 11  deck         203 non-null    category      
 12  embark_town  889 non-null    object        
 13  alive        891 non-null    object        
 14  alone        891 non-null    bool          
 15  date         891 non-null    datetime64[ns]
dtypes: bool(

In [136]:
df_copy['date'].dt.dayofweek # day, month, year ...
# 요일 표시 -> 월요일:0, 일요일:1

0      2
1      2
2      3
3      3
4      4
      ..
886    2
887    3
888    4
889    4
890    5
Name: date, Length: 891, dtype: int32

In [137]:
cond = df_copy['date'].dt.dayofweek == 6
df_copy.loc[cond].head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class who  \
7          0       3    male   2.0      3      1  21.0750        S  Third  아이   
18         0       3  female  31.0      1      0  18.0000        S  Third  여자   
19         1       3  female   NaN      0      0   7.2250        C  Third  여자   
29         0       3    male   NaN      0      0   7.8958        S  Third  남자   
30         0       1    male  40.0      0      0  27.7208        C  First  남자   

    adult_male deck  embark_town alive  alone                date  
7        False  NaN  Southampton    no  False 2025-01-05 09:00:00  
18       False  NaN  Southampton    no  False 2025-01-12 06:00:00  
19       False  NaN    Cherbourg   yes   True 2025-01-12 21:00:00  
29        True  NaN  Southampton    no   True 2025-01-19 03:00:00  
30        True  NaN    Cherbourg    no   True 2025-01-19 18:00:00

## 4. 자전거 데이터 활용

In [22]:
import pandas as pd

df= pd.read_csv('data/seoul_bicycle.csv')
df.head()

대여일자  대여소번호      대여소명  대여구분코드  성별    연령대코드  이용건수      운동량    탄소량  \
0  Jan-20-2020      3      중랑센터  일일(회원)   M  AGE_003     3    61.82   0.52   
1  Jan-20-2020      3      중랑센터  일일(회원)   M  AGE_004     1    39.62   0.28   
2  Jan-20-2020      3      중랑센터      정기   M  AGE_005     3   430.85   4.01   
3  Jan-20-2020      5  상암센터 정비실  일일(회원)  \N  AGE_005     2     1.79   0.02   
4  Jan-20-2020      5  상암센터 정비실      정기   F  AGE_003     1  4501.96  45.47   

       이동거리  이용시간  
0    2230.0    75  
1    1220.0    15  
2   17270.0    53  
3      90.0    33  
4  196010.0    64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   대여일자    327231 non-null  object 
 1   대여소번호   327231 non-null  int64  
 2   대여소명    327231 non-null  object 
 3   대여구분코드  327231 non-null  object 
 4   성별      272841 non-null  object 
 5   연령대코드   327231 non-null  object 
 6   이용건수    327231 non-null  int64  
 7   운동량     327231 non-null  object 
 8   탄소량     327231 non-null  object 
 9   이동거리    327231 non-null  float64
 10  이용시간    327231 non-null  int64  
dtypes: float64(1), int64(3), object(7)
memory usage: 27.5+ MB


In [24]:
df_copy = df.copy()

In [25]:
df_copy['대여일자'] = pd.to_datetime(df_copy['대여일자'], format='%b-%d-%Y')
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   대여일자    327231 non-null  datetime64[ns]
 1   대여소번호   327231 non-null  int64         
 2   대여소명    327231 non-null  object        
 3   대여구분코드  327231 non-null  object        
 4   성별      272841 non-null  object        
 5   연령대코드   327231 non-null  object        
 6   이용건수    327231 non-null  int64         
 7   운동량     327231 non-null  object        
 8   탄소량     327231 non-null  object        
 9   이동거리    327231 non-null  float64       
 10  이용시간    327231 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 27.5+ MB


In [26]:
cond = df_copy['대여일자'].dt.dayofweek == 3
df_copy.loc[cond].head()

대여일자  대여소번호      대여소명   대여구분코드  성별    연령대코드  이용건수     운동량   탄소량  \
53445 2020-02-20      3      중랑센터   일일(회원)   M  AGE_003     5  129.72  1.09   
53446 2020-02-20      3      중랑센터       정기   M  AGE_005     5   151.7   1.4   
53447 2020-02-20      5  상암센터 정비실   일일(회원)  \N  AGE_005    12    11.3  0.12   
53448 2020-02-20      5  상암센터 정비실   일일(회원)   M  AGE_004     6  458.72   4.2   
53449 2020-02-20     10       위트콤  일일(비회원)  \N  AGE_008     1      \N    \N   

          이동거리  이용시간  
53445   4680.0    90  
53446   6080.0   101  
53447    570.0   216  
53448  18100.0   198  
53449      0.0    11

In [27]:
# pd.to_numeic(df_copy['운동량']) # error: 값에 \N이 있어서

In [28]:
df_copy.loc[2344]

대여일자      2020-01-20 00:00:00
대여소번호                     165
대여소명              165. 중앙근린공원
대여구분코드                 일일(회원)
성별                         \N
연령대코드                 AGE_003
이용건수                        1
운동량                        \N
탄소량                        \N
이동거리                      0.0
이용시간                       40
Name: 2344, dtype: object

In [29]:
df_copy['운동량'] = pd.to_numeric(df_copy['운동량'], errors='coerce') # coerce: NaN으로 바꿔줌

In [30]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   대여일자    327231 non-null  datetime64[ns]
 1   대여소번호   327231 non-null  int64         
 2   대여소명    327231 non-null  object        
 3   대여구분코드  327231 non-null  object        
 4   성별      272841 non-null  object        
 5   연령대코드   327231 non-null  object        
 6   이용건수    327231 non-null  int64         
 7   운동량     326830 non-null  float64       
 8   탄소량     327231 non-null  object        
 9   이동거리    327231 non-null  float64       
 10  이용시간    327231 non-null  int64         
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 27.5+ MB


## 5. cut()

In [31]:
bins = [0, 100, 200, 300, df_copy['운동량'].max()]
pd.cut(df_copy['운동량'], bins)

0                 (0.0, 100.0]
1                 (0.0, 100.0]
2         (300.0, 163936052.3]
3                 (0.0, 100.0]
4         (300.0, 163936052.3]
                  ...         
327226    (300.0, 163936052.3]
327227                     NaN
327228            (0.0, 100.0]
327229            (0.0, 100.0]
327230    (300.0, 163936052.3]
Name: 운동량, Length: 327231, dtype: category
Categories (4, interval[float64, right]): [(0.0, 100.0] < (100.0, 200.0] < (200.0, 300.0] < (300.0, 163936052.3]]

In [32]:
pd.cut(df_copy['운동량'], bins=10) # 일정하게 10구간으로 나눔
pd.cut(df_copy['운동량'], bins=10).value_counts() 

운동량
(-163936.052, 16393605.23]      326816
(98361631.38, 114755236.61]          9
(32787210.46, 49180815.69]           2
(16393605.23, 32787210.46]           1
(114755236.61, 131148841.84]         1
(147542447.07, 163936052.3]          1
(81968026.15, 98361631.38]           0
(65574420.92, 81968026.15]           0
(49180815.69, 65574420.92]           0
(131148841.84, 147542447.07]         0
Name: count, dtype: int64

In [33]:
pd.qcut(df_copy['운동량'], q=10) # 비율대로 10구간으로 나눔
pd.qcut(df_copy['운동량'], q=10).value_counts()

운동량
(93.414, 192.02]           32690
(-0.001, 24.737]           32683
(24.737, 93.414]           32683
(601.705, 1079.744]        32683
(1889.606, 3328.186]       32683
(1079.744, 1889.606]       32683
(3328.186, 6805.188]       32683
(6805.188, 163936052.3]    32683
(344.45, 601.705]          32680
(192.02, 344.45]           32679
Name: count, dtype: int64

In [36]:
qcut_bins = [0, 0.2, 0.8, 1] # 데이터의 상위와 하위를 자를 때 사용 가능
df_copy['운동량_한글'] = pd.qcut(df_copy['운동량'], qcut_bins, labels=['적음', '보통', '많음'])
df_copy.head()

대여일자  대여소번호      대여소명  대여구분코드  성별    연령대코드  이용건수      운동량    탄소량  \
0 2020-01-20      3      중랑센터  일일(회원)   M  AGE_003     3    61.82   0.52   
1 2020-01-20      3      중랑센터  일일(회원)   M  AGE_004     1    39.62   0.28   
2 2020-01-20      3      중랑센터      정기   M  AGE_005     3   430.85   4.01   
3 2020-01-20      5  상암센터 정비실  일일(회원)  \N  AGE_005     2     1.79   0.02   
4 2020-01-20      5  상암센터 정비실      정기   F  AGE_003     1  4501.96  45.47   

       이동거리  이용시간 운동량_한글  
0    2230.0    75     적음  
1    1220.0    15     적음  
2   17270.0    53     보통  
3      90.0    33     적음  
4  196010.0    64     많음

# 07. group

In [20]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
df_copy = df.copy()

## 1. groupby()

In [140]:
df_copy.groupby('sex').mean(numeric_only=True)

survived    pclass        age     sibsp     parch       fare  \
sex                                                                    
female  0.742038  2.159236  27.915709  0.694268  0.649682  44.479818   
male    0.188908  2.389948  30.726645  0.429809  0.235702  25.523893   

        adult_male     alone  
sex                           
female    0.000000  0.401274  
male      0.930676  0.712305

In [141]:
df_copy.groupby(['sex', 'pclass']).mean(numeric_only=True)

survived        age     sibsp     parch        fare  \
sex    pclass                                                        
female 1       0.968085  34.611765  0.553191  0.457447  106.125798   
       2       0.921053  28.722973  0.486842  0.605263   21.970121   
       3       0.500000  21.750000  0.895833  0.798611   16.118810   
male   1       0.368852  41.281386  0.311475  0.278689   67.226127   
       2       0.157407  30.740707  0.342593  0.222222   19.741782   
       3       0.135447  26.507589  0.498559  0.224784   12.661633   

               adult_male     alone  
sex    pclass                        
female 1         0.000000  0.361702  
       2         0.000000  0.421053  
       3         0.000000  0.416667  
male   1         0.975410  0.614754  
       2         0.916667  0.666667  
       3         0.919308  0.760807

In [142]:
df_copy.groupby(['sex', 'pclass'])['survived'].mean(numeric_only=True)

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

In [143]:
df_copy.groupby(['sex', 'pclass'])[['survived']].mean(numeric_only=True)

survived
sex    pclass          
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

## 2. reset_index()

In [145]:
df_temp = df_copy.groupby(['sex', 'pclass'])[['survived']].mean()
df_temp

survived
sex    pclass          
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

In [146]:
df_temp.reset_index()

sex  pclass  survived
0  female       1  0.968085
1  female       2  0.921053
2  female       3  0.500000
3    male       1  0.368852
4    male       2  0.157407
5    male       3  0.135447

In [147]:
df_copy.groupby(['sex', 'pclass'])[['survived', 'age']].agg(['mean', 'sum'])

survived            age         
                   mean sum       mean      sum
sex    pclass                                  
female 1       0.968085  91  34.611765  2942.00
       2       0.921053  70  28.722973  2125.50
       3       0.500000  72  21.750000  2218.50
male   1       0.368852  45  41.281386  4169.42
       2       0.157407  17  30.740707  3043.33
       3       0.135447  47  26.507589  6706.42

## 3. pivot_table()

In [148]:
df_copy.pivot_table(index='who', values='survived')

survived
who            
child  0.590361
man    0.163873
woman  0.756458

In [149]:
df_copy.pivot_table(index=['who', 'pclass'], values='survived')

survived
who   pclass          
child 1       0.833333
      2       1.000000
      3       0.431034
man   1       0.352941
      2       0.080808
      3       0.119122
woman 1       0.978022
      2       0.909091
      3       0.491228

# 08. concat

In [37]:
import pandas as pd

df1 = pd.read_csv('data/sales_data1.csv')
df2 = pd.read_csv('data/sales_data2.csv')

In [38]:
df1.head()

index  Transaction ID        Date Product Category  \
0      0           10001  2024-01-01      Electronics   
1      1           10002  2024-01-02  Home Appliances   
2      2           10003  2024-01-03         Clothing   
3      3           10004  2024-01-04            Books   
4      4           10005  2024-01-05  Beauty Products   

              Product Name  Units Sold  Unit Price  Total Revenue  \
0            iPhone 14 Pro           2      999.99        1999.98   
1         Dyson V11 Vacuum           1      499.99         499.99   
2         Levi's 501 Jeans           3       69.99         209.97   
3        The Da Vinci Code           4       15.99          63.96   
4  Neutrogena Skincare Set           1       89.99          89.99   

          Region Payment Method  
0  North America    Credit Card  
1         Europe         PayPal  
2           Asia     Debit Card  
3  North America    Credit Card  
4         Europe         PayPal

In [39]:
df2.head()

index  Transaction ID        Date Product Category  \
0      0           10183  2024-07-01         Clothing   
1      1           10184  2024-07-02            Books   
2      2           10185  2024-07-03  Beauty Products   
3      3           10186  2024-07-04           Sports   
4      4           10187  2024-07-05      Electronics   

                         Product Name  Units Sold  Unit Price  Total Revenue  \
0           Levi's 511 Slim Fit Jeans           3       59.99         179.97   
1            The Martian by Andy Weir           2       12.99          25.98   
2  La Mer Cr챔me de la Mer Moisturizer           1      190.00         190.00   
3                    Polar Vantage V2           1      499.95         499.95   
4                 Sonos Beam Soundbar           1      399.00         399.00   

          Region Payment Method  
0           Asia     Debit Card  
1  North America    Credit Card  
2         Europe         PayPal  
3           Asia    Credit Card  
4  North America    Credit Card

In [40]:
df1.shape

(182, 10)

In [41]:
df2.shape

(58, 10)

## 1. concat()

- *상하/좌우로 연결*

In [44]:
pd.concat([df1, df2]).iloc[180:185] # 연결점 확인

index  Transaction ID        Date Product Category  \
180    180           10181  2024-06-29      Electronics   
181    181           10182  2024-06-30  Home Appliances   
0        0           10183  2024-07-01         Clothing   
1        1           10184  2024-07-02            Books   
2        2           10185  2024-07-03  Beauty Products   

                           Product Name  Units Sold  Unit Price  \
180                 Google Pixelbook Go           1      649.99   
181                   Dyson V8 Absolute           1      399.99   
0             Levi's 511 Slim Fit Jeans           3       59.99   
1              The Martian by Andy Weir           2       12.99   
2    La Mer Cr챔me de la Mer Moisturizer           1      190.00   

     Total Revenue         Region Payment Method  
180         649.99  North America    Credit Card  
181         399.99         Europe         PayPal  
0           179.97           Asia     Debit Card  
1            25.98  North America    Credit Card  
2           190.00         Europe         PayPal

In [45]:
pd.concat([df1, df2], ignore_index=True)

index  Transaction ID        Date Product Category  \
0        0           10001  2024-01-01      Electronics   
1        1           10002  2024-01-02  Home Appliances   
2        2           10003  2024-01-03         Clothing   
3        3           10004  2024-01-04            Books   
4        4           10005  2024-01-05  Beauty Products   
..     ...             ...         ...              ...   
235     53           10236  2024-08-23  Home Appliances   
236     54           10237  2024-08-24         Clothing   
237     55           10238  2024-08-25            Books   
238     56           10239  2024-08-26  Beauty Products   
239     57           10240  2024-08-27           Sports   

                                        Product Name  Units Sold  Unit Price  \
0                                      iPhone 14 Pro           2      999.99   
1                                   Dyson V11 Vacuum           1      499.99   
2                                   Levi's 501 Jeans           3       69.99   
3                                  The Da Vinci Code           4       15.99   
4                            Neutrogena Skincare Set           1       89.99   
..                                               ...         ...         ...   
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99   
236                        Nike Air Force 1 Sneakers           3       90.00   
237           The Handmaid's Tale by Margaret Atwood           3       10.99   
238             Sunday Riley Luna Sleeping Night Oil           1       55.00   
239                       Yeti Rambler 20 oz Tumbler           2       29.99   

     Total Revenue         Region Payment Method  
0          1999.98  North America    Credit Card  
1           499.99         Europe         PayPal  
2           209.97           Asia     Debit Card  
3            63.96  North America    Credit Card  
4            89.99         Europe         PayPal  
..             ...            ...            ...  
235         159.99         Europe         PayPal  
236         270.00           Asia     Debit Card  
237          32.97  North America    Credit Card  
238          55.00         Europe         PayPal  
239          59.98           Asia    Credit Card  

[240 rows x 10 columns]

In [50]:
sales1 = df1.iloc[:, :5] # : 위에서부터 아래 전부, :5 컬럼 5번째까지
sales2 = df2.iloc[:, 5:] # 5: 컬럼 5번째부터

In [52]:
sales1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   index             182 non-null    int64 
 1   Transaction ID    182 non-null    int64 
 2   Date              182 non-null    object
 3   Product Category  182 non-null    object
 4   Product Name      182 non-null    object
dtypes: int64(2), object(3)
memory usage: 7.2+ KB


In [53]:
sales2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Units Sold      58 non-null     int64  
 1   Unit Price      58 non-null     float64
 2   Total Revenue   58 non-null     float64
 3   Region          58 non-null     object 
 4   Payment Method  58 non-null     object 
dtypes: float64(2), int64(1), object(2)
memory usage: 2.4+ KB


In [54]:
pd.concat([sales1, sales2], axis=1)

index  Transaction ID        Date Product Category  \
0        0           10001  2024-01-01      Electronics   
1        1           10002  2024-01-02  Home Appliances   
2        2           10003  2024-01-03         Clothing   
3        3           10004  2024-01-04            Books   
4        4           10005  2024-01-05  Beauty Products   
..     ...             ...         ...              ...   
177    177           10178  2024-06-26            Books   
178    178           10179  2024-06-27  Beauty Products   
179    179           10180  2024-06-28           Sports   
180    180           10181  2024-06-29      Electronics   
181    181           10182  2024-06-30  Home Appliances   

                               Product Name  Units Sold  Unit Price  \
0                             iPhone 14 Pro         3.0       59.99   
1                          Dyson V11 Vacuum         2.0       12.99   
2                          Levi's 501 Jeans         1.0      190.00   
3                         The Da Vinci Code         1.0      499.95   
4                   Neutrogena Skincare Set         1.0      399.00   
..                                      ...         ...         ...   
177  The Sun Also Rises by Ernest Hemingway         NaN         NaN   
178     First Aid Beauty Ultra Repair Cream         NaN         NaN   
179              Oakley Holbrook Sunglasses         NaN         NaN   
180                     Google Pixelbook Go         NaN         NaN   
181                       Dyson V8 Absolute         NaN         NaN   

     Total Revenue         Region Payment Method  
0           179.97           Asia     Debit Card  
1            25.98  North America    Credit Card  
2           190.00         Europe         PayPal  
3           499.95           Asia    Credit Card  
4           399.00  North America    Credit Card  
..             ...            ...            ...  
177            NaN            NaN            NaN  
178            NaN            NaN            NaN  
179            NaN            NaN            NaN  
180            NaN            NaN            NaN  
181            NaN            NaN            NaN  

[182 rows x 10 columns]

## 2. merge()

In [151]:
info = {
    '고객명': ['박세리', '이대호', '손흥민', '김연아', '마이클조던'],
    '생년월일': ['1980-01-02', '1982-02-22', '1993-06-12', '1988-10-16', '1970-03-03'],
    '성별': ['여자', '남자', '남자', '여자', '남자']
}

money = {
    '고객명': ['김연아', '박세리', '손흥민', '이대호', '타이거우즈'],
    '연봉': ['2000원', '3000원', '1500원', '2500원', '3500원']
}

In [152]:
df1 = pd.DataFrame(info)
df2 = pd.DataFrame(money)

In [155]:
pd.merge(df1, df2) # 교집합만 남음, how 기본값이 inner

고객명        생년월일  성별     연봉
0  박세리  1980-01-02  여자  3000원
1  이대호  1982-02-22  남자  2500원
2  손흥민  1993-06-12  남자  1500원
3  김연아  1988-10-16  여자  2000원

In [156]:
pd.merge(df1, df2, how='inner') # inner join

고객명        생년월일  성별     연봉
0  박세리  1980-01-02  여자  3000원
1  이대호  1982-02-22  남자  2500원
2  손흥민  1993-06-12  남자  1500원
3  김연아  1988-10-16  여자  2000원

In [157]:
pd.merge(df1, df2, how='outer') # outer join

고객명        생년월일   성별     연봉
0    김연아  1988-10-16   여자  2000원
1  마이클조던  1970-03-03   남자    NaN
2    박세리  1980-01-02   여자  3000원
3    손흥민  1993-06-12   남자  1500원
4    이대호  1982-02-22   남자  2500원
5  타이거우즈         NaN  NaN  3500원

In [158]:
pd.merge(df1, df2, how='left') # lefr join

고객명        생년월일  성별     연봉
0    박세리  1980-01-02  여자  3000원
1    이대호  1982-02-22  남자  2500원
2    손흥민  1993-06-12  남자  1500원
3    김연아  1988-10-16  여자  2000원
4  마이클조던  1970-03-03  남자    NaN

In [159]:
pd.merge(df1, df2, how='right') # right join

고객명        생년월일   성별     연봉
0    김연아  1988-10-16   여자  2000원
1    박세리  1980-01-02   여자  3000원
2    손흥민  1993-06-12   남자  1500원
3    이대호  1982-02-22   남자  2500원
4  타이거우즈         NaN  NaN  3500원

In [160]:
info = {
    '이름': ['박세리', '이대호', '손흥민', '김연아', '마이클조던'],
    '생년월일': ['1980-01-02', '1982-02-22', '1993-06-12', '1988-10-16', '1970-03-03'],
    '성별': ['여자', '남자', '남자', '여자', '남자']
}

money = {
    '고객명': ['김연아', '박세리', '손흥민', '이대호', '타이거우즈'],
    '연봉': ['2000원', '3000원', '1500원', '2500원', '3500원']
}

In [161]:
df1 = pd.DataFrame(info)
df2 = pd.DataFrame(money)

In [162]:
# pd.merge(df1, df2) # error: 중복되는 컬럼이 없어서 머지 불가능
pd.merge(df1, df2, left_on='이름', right_on='고객명')

이름        생년월일  성별  고객명     연봉
0  박세리  1980-01-02  여자  박세리  3000원
1  이대호  1982-02-22  남자  이대호  2500원
2  손흥민  1993-06-12  남자  손흥민  1500원
3  김연아  1988-10-16  여자  김연아  2000원

In [163]:
# 더 많은 양의 데이터 다뤄보기

In [55]:
movies = pd.read_csv('data/movies.csv')
reviews = pd.read_csv('data/reviews.csv')

In [56]:
movies.head()

movieId  \
0  4517f650-c60a-4edc-b37e-9236213c2b93   
1  9ddacc49-1918-3722-b5d9-4a1fa6b9b2a3   
2  e1374d4d-19b0-31b2-a6cc-c4189f2b27ca   
3  27539355-4940-4c29-aaab-d3fe4dafa4ee   
4  2da44bd6-2a22-3238-a139-a40ab1769550   

                                    movieTitle  movieYear  \
0            Spider-Man: Into the Spider-Verse       2018   
1                              The Incredibles       2004   
2                                Black Panther       2018   
3          Spider-Man: Across the Spider-Verse       2023   
4  Teenage Mutant Ninja Turtles: Mutant Mayhem       2023   

                                            movieURL  movieRank critic_score  \
0  https://www.rottentomatoes.com/m/spider_man_in...          1          97%   
1   https://www.rottentomatoes.com/m/the_incredibles          2          97%   
2  https://www.rottentomatoes.com/m/black_panther...          3          96%   
3  https://www.rottentomatoes.com/m/spider_man_ac...          4          95%   
4  https://www.rottentomatoes.com/m/teenage_mutan...          5          95%   

  audience_score  
0            94%  
1            75%  
2            79%  
3            94%  
4            90%

In [57]:
reviews.head()

movieId  rating  \
0  df35d67b-c89e-30fa-bff5-c31006cc6ae4     5.0   
1  df35d67b-c89e-30fa-bff5-c31006cc6ae4     4.0   
2  df35d67b-c89e-30fa-bff5-c31006cc6ae4     2.0   
3  e70c15a3-eb05-3f65-9988-a1787615d464     5.0   
4  f03e65c8-70e8-34e2-bd3f-1a2efd916f3a     4.0   

                                               quote reviewId  isVerified  \
0  A decent sequel that leaves the door open for ...      NaN       False   
1                           What smells like sulfur?      NaN       False   
2                          dissappointing and stupid      NaN       False   
3  Less campy villains than the first (discountin...      NaN       False   
4           Finally!  One worth watching over again!      NaN       False   

   isSuperReviewer  hasSpoilers  hasProfanity  score creationDate  \
0            False        False         False    5.0   2006-02-10   
1            False        False         False    4.0   2006-02-10   
2            False        False         False    2.0   2006-02-10   
3            False        False         False    5.0   2006-02-10   
4            False        False         False    4.0   2006-02-10   

   userDisplayName userRealm    userId  
0              NaN        RT  34988849  
1              NaN        RT  25114980  
2              NaN        RT  13536103  
3              NaN        RT  38236390  
4              NaN        RT  23716534

In [58]:
movie_review = pd.merge(movies, reviews)
movie_review.head()

movieId     movieTitle  movieYear  \
0  a5479658-16f1-3325-a16a-4181d84a215a        RoboCop       1987   
1  a5479658-16f1-3325-a16a-4181d84a215a        RoboCop       1987   
2  f03e65c8-70e8-34e2-bd3f-1a2efd916f3a  Batman Begins       2005   
3  f03e65c8-70e8-34e2-bd3f-1a2efd916f3a  Batman Begins       2005   
4  f03e65c8-70e8-34e2-bd3f-1a2efd916f3a  Batman Begins       2005   

                                           movieURL  movieRank critic_score  \
0  https://www.rottentomatoes.com/m/1017712-robocop         19          92%   
1  https://www.rottentomatoes.com/m/1017712-robocop         19          92%   
2    https://www.rottentomatoes.com/m/batman_begins         41          85%   
3    https://www.rottentomatoes.com/m/batman_begins         41          85%   
4    https://www.rottentomatoes.com/m/batman_begins         41          85%   

  audience_score  rating                                              quote  \
0            84%     4.0                  Nasty 80s sci-fi, pretty exciting   
1            84%     5.0  OH MAN! POSSIBLY ONE OF THE BEST FILMS IVE EVE...   
2            94%     4.0           Finally!  One worth watching over again!   
3            94%     1.0  I know it's abotu batman and all, but this mov...   
4            94%     5.0                      The best Batman movie to date   

  reviewId  isVerified  isSuperReviewer  hasSpoilers  hasProfanity  score  \
0      NaN       False            False        False         False    4.0   
1      NaN       False            False        False         False    5.0   
2      NaN       False            False        False         False    4.0   
3      NaN       False            False        False         False    1.0   
4      NaN       False            False        False         False    5.0   

  creationDate  userDisplayName userRealm    userId  
0   2006-02-11              NaN        RT  19964219  
1   2006-02-11              NaN        RT  47687302  
2   2006-02-10              NaN        RT  23716534  
3   2006-02-10              NaN        RT  37225455  
4   2006-02-10              NaN        RT  39217567

In [60]:
cond = movie_review['movieYear'] == 2005
movie_review.loc[cond, 'rating'].mean()

np.float64(4.379310344827586)