## 00. numpy

In [3]:
import numpy as np # numpy: 배열 다루기에 특화

- 0차원: 스칼라(scala)
- 1차원: 벡터(vector)
- 2차원: 행렬(matrix)
- 3차원: 텐서(tenser)

In [4]:
a = [
    [1, 2.3, 3],
    [-123, 123, 0]
] # 2차원 리스트
data = np.array(a)
print(data)

[[   1.     2.3    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)
print(data + data)

[[   10.    23.    30.]
 [-1230.  1230.     0.]]
[[   2.     4.6    6. ]
 [-246.   246.     0. ]]


In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


## 1. ndarray 생성하기

- *n차원의 배열*

In [11]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([[1.1, 2.2], [3.3, 4.4, 5.5]]) # error: 안쪽 리스트의 배열이 달라서

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
print(arr1.ndim) # n차원
print(arr2.ndim)

1
2


In [14]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [15]:
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.zeros((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [16]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 2. ndarray 자료형

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype=np.float64) # 생성할 때 속성을 넣어서 형변환
arr3 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
int32


In [19]:
float_arr1 = arr1.astype(np.float64) # 명시적 형변환
print(arr1)
print(float_arr1)
print(float_arr1.dtype)

[1 2 3]
[1. 2. 3.]
float64


In [20]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 형변환 시 소수점 버림
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 3. 산술 연산

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) # 같은 위치에 있는 데이터끼리 사칙연산
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [22]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[ True False False]
 [False False  True]]


## 4. 색인(인덱싱)과 슬라이싱

In [23]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [25]:
arr[2:5] = 10
print(arr) # 원본이 변함

[ 0  1 10 10 10  5  6  7  8  9]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][1])
print(arr[1, 1])

[[1 2 3]
 [4 5 6]]
5
5


In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [31]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [34]:
arr3d[:1, 1:, 2:] # 슬라이싱 접근 대괄호 유지

array([[[6],
        [9]]])

In [37]:
arr3d[0, 1:, 2:] # 인덱스 접근 대괄호 -1

array([[6],
       [9]])

In [38]:
arr3d[0, 1:, 2:] = 999
print(arr3d)

[[[  1   2   3]
  [  4   5 999]
  [  7   8 999]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]]


## 5. 불리언 값으로 선택

In [39]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [40]:
names == 'hong'

array([ True, False,  True, False])

In [41]:
data[[True, False, True, False]]

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [42]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [43]:
names = np.array(['hong', 'kim', 'kim', 'hong'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [44]:
data[names == 'hong'] # 순서로 고름

array([['math', '60'],
       ['eng', '50']], dtype='<U21')

In [46]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '50']
[['math']
 ['eng']]


In [47]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True  True False]
[False  True  True False]


In [48]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '70']], dtype='<U21')

## 6. 팬시 색인 (fancy indexing)

In [49]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [50]:
arr[[4, 3, 0, 5]] # 대괄호 안 대괄호 -> 내가 원하는 행을 직접 고를 수 있음

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [51]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [52]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [58]:
print(arr[[1, 5], [2, 3]])

[ 6 23]


In [59]:
print(arr[[1, 5], [1, 2]])

[ 5 22]


In [63]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])