## 00. numpy

In [2]:
import numpy as np # numpy: 배열 다루기에 특화

- 0차원: 스칼라(scala)
- 1차원: 벡터(vector)
- 2차원: 행렬(matrix)
- 3차원: 텐서(tenser)

In [4]:
a = [
    [1, 2.3, 3],
    [-123, 123, 0]
] # 2차원 리스트
data = np.array(a)
print(data)

[[   1.     2.3    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)
print(data + data)

[[   10.    23.    30.]
 [-1230.  1230.     0.]]
[[   2.     4.6    6. ]
 [-246.   246.     0. ]]


In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


## 1. ndarray 생성하기

- *n차원의 배열*

In [11]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([[1.1, 2.2], [3.3, 4.4, 5.5]]) # error: 안쪽 리스트의 배열이 달라서

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
print(arr1.ndim) # n차원
print(arr2.ndim)

1
2


In [14]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [15]:
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.zeros((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [16]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 2. ndarray 자료형

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype=np.float64) # 생성할 때 속성을 넣어서 형변환
arr3 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float64
int32


In [19]:
float_arr1 = arr1.astype(np.float64) # 명시적 형변환
print(arr1)
print(float_arr1)
print(float_arr1.dtype)

[1 2 3]
[1. 2. 3.]
float64


In [20]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 형변환 시 소수점 버림
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 3. 산술 연산

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) # 같은 위치에 있는 데이터끼리 사칙연산
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [22]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[ True False False]
 [False False  True]]


## 4. 색인(인덱싱)과 슬라이싱

In [23]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [25]:
arr[2:5] = 10
print(arr) # 원본이 변함

[ 0  1 10 10 10  5  6  7  8  9]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][1])
print(arr[1, 1])

[[1 2 3]
 [4 5 6]]
5
5


In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [31]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [34]:
arr3d[:1, 1:, 2:] # 슬라이싱 접근 대괄호 유지

array([[[6],
        [9]]])

In [37]:
arr3d[0, 1:, 2:] # 인덱스 접근 대괄호 -1

array([[6],
       [9]])

In [38]:
arr3d[0, 1:, 2:] = 999
print(arr3d)

[[[  1   2   3]
  [  4   5 999]
  [  7   8 999]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]]


## 5. 불리언 값으로 선택

In [39]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [40]:
names == 'hong'

array([ True, False,  True, False])

In [41]:
data[[True, False, True, False]]

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [42]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [43]:
names = np.array(['hong', 'kim', 'kim', 'hong'])
data = np. array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [44]:
data[names == 'hong'] # 순서로 고름

array([['math', '60'],
       ['eng', '50']], dtype='<U21')

In [46]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '50']
[['math']
 ['eng']]


In [47]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True  True False]
[False  True  True False]


In [48]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '70']], dtype='<U21')

## 6. 팬시 색인 (fancy indexing)

In [49]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [50]:
arr[[4, 3, 0, 5]] # 대괄호 안 대괄호 -> 내가 원하는 행을 직접 고를 수 있음

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [51]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [52]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [58]:
print(arr[[1, 5], [2, 3]])

[ 6 23]


In [59]:
print(arr[[1, 5], [1, 2]])

[ 5 22]


In [63]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 7. 배열 전치

In [3]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(arr.T) # 축을 바꿀 때

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
# 행렬의 내적, 곱 연산
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## 8. numpy 함수

In [7]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[-0.70258835 -0.34174114  0.65235979]
 [ 0.71713773  0.5360125  -2.08544605]
 [ 1.06071122 -0.38576056  0.44127118]]


In [8]:
arr1 = np.sqrt(samples) # 루트에 루트 씌우면 결측치(nan: not a number)
print(arr1)

[[       nan        nan 0.80768793]
 [0.84683985 0.73212875        nan]
 [1.02990835        nan 0.66428245]]


C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1273485535.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [9]:
arr2 = np.abs(samples) # absolute: 절댓값
print(arr2)

[[0.70258835 0.34174114 0.65235979]
 [0.71713773 0.5360125  2.08544605]
 [1.06071122 0.38576056 0.44127118]]


In [11]:
np.isnan(arr1) # 결측치 찾기

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False]])

# 01. data structure

## 1. Series

- pandas에서 사용하는 1차원 배열
- index를 사용할 수 있음

In [1]:
import pandas as pd
import numpy as np

In [13]:
arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [14]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [16]:
s = pd.Series(arr, dtype='float32')
print(s)

0    100.0
1    101.0
2    102.0
3    103.0
4    104.0
5    105.0
6    106.0
7    107.0
8    108.0
9    109.0
dtype: float32


In [18]:
s = pd.Series(['kim', 'lee', 'park'])
print(s) # pandas에서 object = str

0     kim
1     lee
2    park
dtype: object


In [19]:
s = pd.Series([1, 2, 3, '1', '2', 'hello'])
print(s) # object: 포괄적인 데이터 타입

0        1
1        2
2        3
3        1
4        2
5    hello
dtype: object


In [20]:
s[5]

'hello'

In [21]:
s[-1] # errpr: 음수 인덱싱 X

KeyError: -1

In [22]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [23]:
names = pd.Series(['kim', 'lee', 'park'], index=['a', 'b', 'c'])
names # 인덱스가 숫자가 아니어도 됨

a     kim
b     lee
c    park
dtype: object

In [24]:
names[0] # 인덱싱 가능하지만 가능하면 iloc 사용

C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1035344546.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  names[0]


'kim'

In [25]:
names.iloc[0] # index location

'kim'

In [26]:
names['a']

'kim'

In [27]:
names.index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
names.values

array(['kim', 'lee', 'park'], dtype=object)

In [29]:
names.ndim

1

In [30]:
names.shape

(3,)

## 2. NaN (Not a Number)

In [32]:
s = pd.Series([1, 2, 3, np.nan])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


## 3. fancy indexing

In [33]:
f = ['banana', 'apple', 'grape', np.nan]
s = pd.Series(f, index=list('abcd'))
print(s)

a    banana
b     apple
c     grape
d       NaN
dtype: object


In [34]:
s[['d', 'a']]

d       NaN
a    banana
dtype: object

In [35]:
s[[3, 1]] # 숫자 쓸 땐 iloc 사용

C:\Users\1-14\AppData\Local\Temp\ipykernel_7984\1367491741.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[3, 1]]


d      NaN
b    apple
dtype: object

In [36]:
s.iloc[[3, 1]]

d      NaN
b    apple
dtype: object

## 4. bool indexing

In [37]:
s

a    banana
b     apple
c     grape
d       NaN
dtype: object

In [38]:
s[[True, False, True, False]]

a    banana
c     grape
dtype: object

In [39]:
s == 'banana'

a     True
b    False
c    False
d    False
dtype: bool

In [40]:
s[s == 'banana']

a    banana
dtype: object

In [41]:
s = pd.Series([1, 5, 3, 4, 2, 6])
s[s > 3]

1    5
3    4
5    6
dtype: int64

## 5. 결측치(NaN) 처리

In [42]:
s = pd.Series([1, 3, np.nan, 10, 11, np.nan])
print(s)

0     1.0
1     3.0
2     NaN
3    10.0
4    11.0
5     NaN
dtype: float64


In [43]:
s. isnull()
s. isna()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [44]:
s[s.isnull()]
s[s.isna()]

2   NaN
5   NaN
dtype: float64

In [45]:
s[s.notnull()]
s[s.notna()]

0     1.0
1     3.0
3    10.0
4    11.0
dtype: float64

## 6. Slicing

In [46]:
s[1:3]

1    3.0
2    NaN
dtype: float64

In [48]:
s = pd.Series([1, 2, 3], index=list('abc'))
print(s[1:2])
print(s['a':'b']) # 글자는 이상 미만이 안됨

b    2
dtype: int64
a    1
b    2
dtype: int64


## 7. DataFrame

- 2차원 데이터구조 (excel, sheet와 유사)
- 행(row), 열(column) 구조

In [2]:
d = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
d

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
d = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], columns=list('가나다'))
d

가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
info = {
    'name': ['kim', 'lee', 'park'],
    'age' : [10, 20, 30]
}

In [6]:
info_df = pd.DataFrame(info)
info_df

name  age
0   kim   10
1   lee   20
2  park   30

In [8]:
info_df.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
info_df.columns

Index(['name', 'age'], dtype='object')

In [11]:
info_df.values

array([['kim', 10],
       ['lee', 20],
       ['park', 30]], dtype=object)

In [12]:
info_df.dtypes

name    object
age      int64
dtype: object

In [13]:
info_df.T

0    1     2
name  kim  lee  park
age    10   20    30

## 8. index 지정

In [14]:
info_df.index = list('abc')
info_df

name  age
a   kim   10
b   lee   20
c  park   30

## 9. column 다루기

In [15]:
info_df.columns

Index(['name', 'age'], dtype='object')

In [16]:
print(info_df['name'])
print(type(info_df['name']))

a     kim
b     lee
c    park
Name: name, dtype: object
<class 'pandas.core.series.Series'>


In [17]:
info_df[['age', 'name']] # column의 fancy indexing

age  name
a   10   kim
b   20   lee
c   30  park

In [18]:
info_df = info_df.rename(columns={'name': '이름'}) # 재할당해서 원본 변경
info_df

이름  age
a   kim   10
b   lee   20
c  park   30

In [19]:
info_df.rename(columns={'이름': 'last name'}, inplace=True) # 바로 변경
info_df

last name  age
a       kim   10
b       lee   20
c      park   30

# 02. file load save

In [20]:
import numpy as np
import pandas as pd

## 1. excel

```python
excel = pd.read_excel('파일위치/파일명.xlsx') # 불러오기
excel[['colum1', 'column2', ...]] # indexing
excel.head()
excel = pd.read_excel('data/excel.xlsx', sheet_name=None) # dictionary
excel = pd.read_excel('data/excel.xlsx', sheet_name='시트이름')
excel.to_excel('파일위치/파일명.xlsx', index=False) # 저장
```

## 2. CSV

```python
df = pd.read_csv('파일위치/파일명.csv')
df.to_csv('파일위치/파일명.csv')
```

# 03. query

In [24]:
import pandas as pd
import seaborn as sns

In [26]:
df = sns.load_dataset('titanic')

## 1. head(), tail()

In [27]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [28]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

## 2. info()

In [29]:
df.info()
# non-null: 결측치가 아닌 정보를 세어줌
# category: 분류가 되는 데이터

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


## 3. value_counts()

In [30]:
df['who']

0        man
1      woman
2      woman
3      woman
4        man
       ...  
886      man
887    woman
888    woman
889      man
890      man
Name: who, Length: 891, dtype: object

In [31]:
print(type(df['who'])) # column 1개 = Series

<class 'pandas.core.series.Series'>


In [32]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

## 4. Attribute

In [33]:
df.ndim # dataframe은 사실상 모두 2차원

2

In [34]:
df.shape # 데이터 891개, 칼럼 15개

(891, 15)

In [35]:
df.index # 데이터의 개수

RangeIndex(start=0, stop=891, step=1)

In [38]:
df.columns # 칼럼만 보기

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [39]:
df.values # 값만 보기

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]],
      shape=(891, 15), dtype=object)

## 5. 타입 변환 (astype)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [41]:
df['pclass'].astype('int32')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int32

In [42]:
df['pclass'].astype('str')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: object

In [43]:
df['pclass'].astype('category')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: category
Categories (3, int64): [1, 2, 3]

## 6. 정렬

### 6.1. sort_index()